export const CREATE_REMINDER = '[REMINDERS] CREATE_REMINDER';
export const DELETE_REMINDER = '[REMINDERS] DELETE_REMINDER';
export const UPDATE_REMINDER = '[REMINDERS] UPDATE_REMINDER';
export const GET_ALL_REMINDERS = '[REMINDERS] GET_ALL_REMINDERS';
