export const CREATE_REMINDER = '[REMINDERS] CREATE_REMINDER';
export const DELETE_REMINDER = '[REMINDERS] DELETE_REMINDER';
export const UPDATE_REMINDER = '[REMINDERS] UPDATE_REMINDER';
export const GET_ALL_REMINDERS = '[REMINDERS] GET_ALL_REMINDERS';
export const GET_SINGLE_REMINDER = '[REMINDERS] GET_SINGLE_REMINDER';
export const GET_UPCOMING_REMINDERS = '[REMINDERS] GET_UPCOMING_REMINDERS';
export const SET_ACTIVE_REMINDER = '[REMINDERS] SET_ACTIVE_REMINDER';
