export const SIGN_IN_USER = '[AUTH] SIGN_IN_USER';
export const SIGN_UP_USER = '[AUTH] SIGN_UP_USER';
export const RESET_PASSWORD = '[AUTH] RESET_PASSWORD';
export const FORGOT_PASSWORD = '[AUTH] FORGOT_PASSWORD';
